schema_version = "1.0.0"

id = "simple_renaming_panel"
version = "2.1.1"
name = "Simple Renaming Panel"
tagline = "Effortlessly rename multiple objects with this simple addon"
maintainer = "Matthias Patscheider <patscheider.matthias@gmail.com>"
type = "add-on"

website = "https://weisl.github.io/renaming/"

tags = ["3D View", "Scene", "User Interface"]

blender_version_min = "4.2.0"

license = [
    "SPDX:GPL-3.0-or-later",
]

copyright = [
    "2024 Matthias Patscheider",
]

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "/.git/",
    "/*.zip",
]