name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: simple_renaming  # Checkout directly into a folder named "simple_renaming"

      - name: Read version from blender_manifest.toml
        id: version
        run: |
          manifest_version=$(grep '^version' simple_renaming/blender_manifest.toml | sed 's/version = "\(.*\)"/\1/')
          echo "manifest_version=$manifest_version" >> $GITHUB_OUTPUT

      - name: Read version from blender_manifest.toml
        id: version
        run: |
          VERSION=$(python3 -c "import tomllib; f=open('${{ github.event.repository.name }}/blender_manifest.toml','rb'); print(tomllib.load(f)['version'])")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set short SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Zip addon
        run: |
          zip -r simple_renaming_v${{ steps.version.outputs.manifest_version }}_${{ steps.vars.outputs.short_sha }}.zip \
            simple_renaming \
            -x "simple_renaming/.git*" \
            -x "simple_renaming/.*/*" \
            -x "simple_renaming/tests/*" \
            -x "simple_renaming/venv/*"

      - name: Upload zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: simple_renaming_v${{ steps.version.outputs.manifest_version }}_${{ steps.vars.outputs.short_sha }}
          path: simple_renaming_v${{ steps.version.outputs.manifest_version }}_${{ steps.vars.outputs.short_sha }}.zip
          retention-days: 7
